# Generated by Django 6.1.1 on 2026-10-06 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('contenido', models.TextField(blank=True, verbose_name='Material formativo (texto)')),
                ('material_url', models.URLField(blank=True, verbose_name='Enlace al material')),
                ('duracion_horas', models.PositiveSmallIntegerField(default=1, verbose_name='Duración (horas)')),
                ('obligatorio', models.BooleanField(default=False, help_text='Se asigna automáticamente a nuevos colaboradores.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curso de capacitación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('SALA', 'Sala de juntas'), ('AUDIOVISUAL', 'Recurso audiovisual'), ('ESPACIO', 'Espacio físico')], default='SALA', max_length=12)),
                ('capacidad', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sede__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ciudad', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento de identidad')),
                ('cargo', models.CharField(max_length=120)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Término indefinido'), ('FIJO', 'Término fijo'), ('OBRA', 'Obra o labor'), ('APRENDIZAJE', 'Aprendizaje')], default='INDEFINIDO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('rol', models.CharField(choices=[('ADMIN', 'Superadministrador'), ('RH', 'Líder de Recursos Humanos'), ('IT', 'Líder de Tecnología (IT)'), ('FINANZAS', 'Líder Financiero'), ('OPERACIONES', 'Líder de Operaciones y Logística'), ('EMPLEADO', 'Colaborador')], default='EMPLEADO', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('firma_x', models.TextField(blank=True, verbose_name='Firma X')),
                ('firma_actualizada', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.sede')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORTATIL', 'Portátil'), ('ESCRITORIO', 'Equipo de escritorio'), ('MONITOR', 'Monitor'), ('CELULAR', 'Celular'), ('PERIFERICO', 'Periférico'), ('OTRO', 'Otro')], max_length=12)),
                ('marca_modelo', models.CharField(max_length=120, verbose_name='Marca / modelo')),
                ('serial', models.CharField(max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=14)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='core.empleado')),
            ],
            options={
                'verbose_name': 'activo tecnológico',
                'ordering': ['tipo', 'marca_modelo'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('COMUNICADO', 'Comunicado oficial'), ('AVISO', 'Aviso institucional'), ('NOVEDAD', 'Novedad')], default='COMUNICADO', max_length=12)),
                ('destacada', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='core.empleado')),
            ],
            options={
                'verbose_name': 'noticia corporativa',
                'ordering': ['-destacada', '-creada'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Motivo / reunión')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cancelada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.empleado')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.espacio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='espacio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='core.sede'),
        ),
        migrations.CreateModel(
            name='SolicitudAnticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('comentario_revision', models.CharField(blank=True, max_length=300, verbose_name='Comentario de revisión')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ANTICIPO', 'Anticipo de nómina'), ('PRESTAMO', 'Préstamo')], default='ANTICIPO', max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveSmallIntegerField(default=1, help_text='Número de cuotas de descuento (1 a 24).')),
                ('justificacion', models.CharField(max_length=300, verbose_name='Justificación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='core.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.empleado')),
            ],
            options={
                'verbose_name': 'solicitud de anticipo/préstamo',
                'ordering': ['-creado'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('comentario_revision', models.CharField(blank=True, max_length=300, verbose_name='Comentario de revisión')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso'), ('LICENCIA', 'Licencia')], default='VACACIONES', max_length=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='core.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.empleado')),
            ],
            options={
                'verbose_name': 'solicitud de vacaciones/permiso',
                'ordering': ['-creado'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Falla de hardware'), ('SOFTWARE', 'Falla de software'), ('ACCESOS', 'Accesos y cuentas')], max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=8)),
                ('asunto', models.CharField(max_length=160)),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('solucion', models.TextField(blank=True, verbose_name='Respuesta / solución')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='core.empleado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.empleado')),
            ],
            options={
                'verbose_name': 'ticket de soporte',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=10)),
                ('asignado', models.DateTimeField(auto_now_add=True)),
                ('completado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.cursocapacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.empleado')),
            ],
            options={
                'ordering': ['estado', '-asignado'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'empleado'), name='un_curso_por_empleado')],
            },
        ),
        migrations.CreateModel(
            name='ExtractoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes liquidado')),
                ('devengado_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deduccion_salud', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deduccion_pension', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractos', to='core.empleado')),
            ],
            options={
                'ordering': ['-periodo', 'empleado__user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'periodo'), name='un_extracto_por_periodo')],
            },
        ),
    ]
